In [4]:
import torch
v1 = torch.arange(4)
v2 = torch.arange(4, 8)
print(v1)
print(v2)
print(torch.outer(v1, v2))
print(v1[:, None])
print(v2[None, :])

tensor([0, 1, 2, 3])
tensor([4, 5, 6, 7])
tensor([[ 0,  0,  0,  0],
        [ 4,  5,  6,  7],
        [ 8, 10, 12, 14],
        [12, 15, 18, 21]])
tensor([[0],
        [1],
        [2],
        [3]])
tensor([[4, 5, 6, 7]])


In [10]:
import torch
v1 = torch.arange(10)
print(type(v1.max(dim=-1, keepdim=True)))
print(type(v1.sum(dim=-1, keepdim=True)))

<class 'torch.return_types.max'>
<class 'torch.Tensor'>
